// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAK2kGxwPjC9ha4BL2lN-cDLX8CcPB1SE',
    appId: '1:908965807410:web:3060f4be3d58abfdc4032b',
    messagingSenderId: '908965807410',
    projectId: 'myappnew-2997d',
    authDomain: 'myappnew-2997d.firebaseapp.com',
    storageBucket: 'myappnew-2997d.firebasestorage.app',
    measurementId: 'G-1V4MT6TG5P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2wbU19DE8-JSCPWylQ9gRHK4CSHCP9B4',
    appId: '1:908965807410:android:999b03b9617894b3c4032b',
    messagingSenderId: '908965807410',
    projectId: 'myappnew-2997d',
    storageBucket: 'myappnew-2997d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzL2cqsqkSUf2fTPK8NyhW_PTMSazAUdk',
    appId: '1:908965807410:ios:bb85ffbb2b6e7f87c4032b',
    messagingSenderId: '908965807410',
    projectId: 'myappnew-2997d',
    storageBucket: 'myappnew-2997d.firebasestorage.app',
    iosBundleId: 'com.example.myAppNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzL2cqsqkSUf2fTPK8NyhW_PTMSazAUdk',
    appId: '1:908965807410:ios:bb85ffbb2b6e7f87c4032b',
    messagingSenderId: '908965807410',
    projectId: 'myappnew-2997d',
    storageBucket: 'myappnew-2997d.firebasestorage.app',
    iosBundleId: 'com.example.myAppNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAK2kGxwPjC9ha4BL2lN-cDLX8CcPB1SE',
    appId: '1:908965807410:web:661402e45aa9c605c4032b',
    messagingSenderId: '908965807410',
    projectId: 'myappnew-2997d',
    authDomain: 'myappnew-2997d.firebaseapp.com',
    storageBucket: 'myappnew-2997d.firebasestorage.app',
    measurementId: 'G-ZSCNELPXCY',
  );
}
